name: Node.js Bump Version

on:
  workflow_dispatch:

jobs:

  increment-version:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout the main
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ github.token }}
          
      - name: Setup git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "BuildMan"
      
      - name: Auto increment version
        run: npm version patch -m "[Build] Bump version to %s"
      
      - run: git push
